name: run script
on: [push]
jobs:
  run_tests:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Run script file
        run: |
          chmod +x ./public/scripts/test.bat
          ./public/scripts/test.bat
        shell: pwsh




